using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TrainingIS.DAL;
using TrainingIS.Entities;
using TrainingIS.BLL;
using TrainingIS.BLL.Exceptions;
using GApp.DAL.ReadExcel;
using ClosedXML.Excel;
using System.IO;
using static TrainingIS.WebApp.Enums.Enums;
using TrainingIS.Entities.Resources.AbsenceResources;
using TrainingIS.WebApp.Helpers;
using GApp.DAL.Exceptions;
using TrainingIS.WebApp.Manager.Views.msgs;

namespace TrainingIS.WebApp.Controllers
{
    // Generated by Manager v 0.1.4
    public class BaseAbsencesController : BaseController
    {
        protected AbsenceBLO absenceBLO = null;

		public BaseAbsencesController()
        {
            this.msgHelper = new MsgViews(typeof(Absence));
			this.absenceBLO = new AbsenceBLO(this._UnitOfWork);
        }

        public virtual ActionResult Index()
        {
		   msgHelper.Index(msg);
           return View(absenceBLO.FindAll());
        }

        public virtual ActionResult Details(long? id)
        {
		    msgHelper.Details(msg);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Absence absence = absenceBLO.FindBaseEntityByID((long) id);
            if (absence == null)
            {
                return HttpNotFound();
            }
            return View(absence);
        }

        public virtual ActionResult Create()
        {
		   msgHelper.Create(msg);
			
            ViewBag.SeanceTrainingId = new SelectList(new SeanceTrainingBLO(this._UnitOfWork).FindAll(), "Id", "Reference");
			
            ViewBag.TraineeId = new SelectList(new TraineeBLO(this._UnitOfWork).FindAll(), "Id", "FirstName");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public virtual ActionResult Create([Bind(Include = "Id,TraineeId,isHaveAuthorization,SeanceTrainingId,FormerComment,TraineeComment,SupervisorComment,CreateDate,UpdateDate")] Absence absence)
        {
			
            if (ModelState.IsValid)
            {

				try
                {
                    absenceBLO.Save(absence);
                }
                catch (GAppDataBaseException ex)
                {
                    msgHelper.Create(msg);
                    Alert(ex.Message, NotificationType.error);
                    return View(absence);
                }
                
				Alert(string.Format(msgManager.The_Entity_was_well_created, msg_Absence.SingularName, absence), NotificationType.success);
                return RedirectToAction("Index");
            }
			msgHelper.Create(msg);
            ViewBag.SeanceTrainingId = new SelectList(new SeanceTrainingBLO(this._UnitOfWork).FindAll(), "Id", "Reference", absence.SeanceTrainingId);
            ViewBag.TraineeId = new SelectList(new TraineeBLO(this._UnitOfWork).FindAll(), "Id", "FirstName", absence.TraineeId);
		    Alert(msgManager.The_information_you_have_entered_is_not_valid, NotificationType.warning);
            return View(absence);
        }

        public virtual ActionResult Edit(long? id)
        {
			msgHelper.Edit(msg);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Absence absence = absenceBLO.FindBaseEntityByID((long)id);
            if (absence == null)
            {
                return HttpNotFound();
            }
            ViewBag.SeanceTrainingId = new SelectList(new SeanceTrainingBLO(this._UnitOfWork).FindAll(), "Id", "Reference", absence.SeanceTrainingId);
            ViewBag.TraineeId = new SelectList(new TraineeBLO(this._UnitOfWork).FindAll(), "Id", "FirstName", absence.TraineeId);
            return View(absence);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public virtual ActionResult Edit([Bind(Include = "Id,TraineeId,isHaveAuthorization,SeanceTrainingId,FormerComment,TraineeComment,SupervisorComment,CreateDate,UpdateDate")] Absence absence)
        {
            if (ModelState.IsValid)
            {
                Absence old_absence = absenceBLO.FindBaseEntityByID(absence.Id);
                UpdateModel(old_absence);

				try
                {
                    absenceBLO.Save(old_absence);
                }
                catch (GAppDataBaseException ex)
                {
                    msgHelper.Edit(msg); ;
                    Alert(ex.Message, NotificationType.error);
                    return View(absence);
                }

				Alert(string.Format(msgManager.The_entity_has_been_changed, msg_Absence.SingularName, absence), NotificationType.success);
                return RedirectToAction("Index");
            }
            ViewBag.SeanceTrainingId = new SelectList(new SeanceTrainingBLO(this._UnitOfWork).FindAll(), "Id", "Reference", absence.SeanceTrainingId);
            ViewBag.TraineeId = new SelectList(new TraineeBLO(this._UnitOfWork).FindAll(), "Id", "FirstName", absence.TraineeId);

            msgHelper.Edit(msg);
			Alert(msgManager.The_information_you_have_entered_is_not_valid, NotificationType.warning);
            return View(absence);
        }

        public virtual ActionResult Delete(long? id)
        {
			msgHelper.Delete(msg);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Absence absence = absenceBLO.FindBaseEntityByID((long)id);
            if (absence == null)
            {
                return HttpNotFound();
            }
            return View(absence);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public virtual ActionResult DeleteConfirmed(long id)
        {
			Absence absence = absenceBLO.FindBaseEntityByID((long)id);
            absenceBLO.Delete(absence);

			 

			Alert(string.Format(msgManager.The_entity_has_been_removed, msg_Absence.SingularName, absence), NotificationType.success);
            return RedirectToAction("Index");
        }

		public virtual ActionResult Import()
        {
            //Save excel file to server
            HttpPostedFileBase parametersTemplate = Request.Files["import_objects"];

            // [Bug] if multiple user import the same file in the same moments
            string path = Server.MapPath("~/Content/Files/Upload" + parametersTemplate.FileName);
            if (System.IO.File.Exists(path))
            {
                System.IO.File.Delete(path);
                parametersTemplate.SaveAs(path);
            }
            parametersTemplate.SaveAs(path);

            //Save new parameters to database
            var excelData = new ExcelData(path); // link to other project
            DataTable firstTable = excelData.getFirstTable();

			try
            {
                string msg =   absenceBLO.Import(firstTable).ToString().ToString().ToString();
                Message(msg, NotificationType.info);
               
            }
            catch (ImportException e)
            {
                Message(e.Message, NotificationType.info);
            }
			 return RedirectToAction("Index");
        }


        public virtual FileResult Export()
        {
            using (XLWorkbook wb = new XLWorkbook())
            {
                DataTable dataTable = absenceBLO.Export();
                wb.Worksheets.Add(dataTable);
                using (MemoryStream stream = new MemoryStream())
                {
                    wb.SaveAs(stream);
                    return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", msg_Absence.PluralName + ".xlsx");
                }
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                absenceBLO.Dispose();
            }
            base.Dispose(disposing);
        }
    }

	public partial class AbsencesController : BaseAbsencesController{};
}
