using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TrainingIS.DAL;
using TrainingIS.Entities;
using TrainingIS.BLL;
using GApp.DAL.ReadExcel;
using ClosedXML.Excel;
using System.IO;
using static TrainingIS.WebApp.Enums.Enums;
using TrainingIS.Entities.Resources.FormerResources;
using TrainingIS.WebApp.Helpers.msgs;

namespace TrainingIS.WebApp.Controllers
{
    // Generated by Manager v 0.0.4
    public class FormersController : BaseController
    {
        private FormerBLO formerBLO = new FormerBLO();

        public ActionResult Index()
        {
           return View(formerBLO.FindAll());
        }

        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Former former = formerBLO.FindBaseEntityByID((long) id);
            if (former == null)
            {
                return HttpNotFound();
            }
            return View(former);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,FirstName,LastName,Sex,CIN,Cellphone,Email,Address,FaceBook,WebSite,RegistrationNumber")] Former former)
        {
            if (ModelState.IsValid)
            {
                formerBLO.Save(former);
				Alert(string.Format(msgManager.The_Entity_was_well_created, msg_Former.SingularName, former), NotificationType.success);
                return RedirectToAction("Index");
            }

		    Alert(msgManager.The_information_you_have_entered_is_not_valid, NotificationType.warning);
            return View(former);
        }

        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Former former = formerBLO.FindBaseEntityByID((long)id);
            if (former == null)
            {
                return HttpNotFound();
            }
            return View(former);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FirstName,LastName,Sex,CIN,Cellphone,Email,Address,FaceBook,WebSite,RegistrationNumber")] Former former)
        {
            if (ModelState.IsValid)
            {
                Former old_former = formerBLO.FindBaseEntityByID(former.Id);
                UpdateModel(old_former);
                formerBLO.Save(old_former);
				Alert(string.Format(msgManager.The_entity_has_been_changed, msg_Former.SingularName, former), NotificationType.success);
                return RedirectToAction("Index");
            }

			Alert(msgManager.The_information_you_have_entered_is_not_valid, NotificationType.warning);
            return View(former);
        }

        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Former former = formerBLO.FindBaseEntityByID((long)id);
            if (former == null)
            {
                return HttpNotFound();
            }
            return View(former);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
			Former former = formerBLO.FindBaseEntityByID((long)id);
            formerBLO.Delete(former);

			 

			Alert(string.Format(msgManager.The_entity_has_been_removed, msg_Former.SingularName, former), NotificationType.success);
            return RedirectToAction("Index");
        }

		public ActionResult Import()
        {
            //Save excel file to server
            HttpPostedFileBase parametersTemplate = Request.Files["import_objects"];

            // [Bug] if multiple user import the same file in the same moments
            string path = Server.MapPath("~/Content/Files/Upload" + parametersTemplate.FileName);
            if (System.IO.File.Exists(path))
            {
                System.IO.File.Delete(path);
                parametersTemplate.SaveAs(path);
            }
            parametersTemplate.SaveAs(path);

            //Save new parameters to database
            var excelData = new ExcelData(path); // link to other project
            DataTable firstTable = excelData.getFirstTable();

			try
            {
                string msg =   formerBLO.Import(firstTable);
                Message(msg, NotificationType.info);
                
            }
            catch (ImportLineException e)
            {
                Message(e.Message, NotificationType.info);
            }
            return RedirectToAction("Index");
        }


        public FileResult Export()
        {
            using (XLWorkbook wb = new XLWorkbook())
            {
                DataTable dataTable = formerBLO.Export();
                wb.Worksheets.Add(dataTable);
                using (MemoryStream stream = new MemoryStream())
                {
                    wb.SaveAs(stream);
                    return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", msg_Former.PluralName + ".xlsx");
                }
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                formerBLO.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}
