using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TrainingIS.DAL;
using TrainingIS.Entities;
using TrainingIS.BLL;
using TrainingIS.BLL.Exceptions;
using GApp.DAL.ReadExcel;
using ClosedXML.Excel;
using System.IO;
using static TrainingIS.WebApp.Enums.Enums;
using TrainingIS.Entities.Resources.ModuleTrainingResources;
using TrainingIS.WebApp.Helpers.msgs;
using TrainingIS.WebApp.Helpers;
using GApp.DAL.Exceptions;

namespace TrainingIS.WebApp.Controllers
{
    // Generated by Manager v 0.1.4
    public class BaseModuleTrainingsController : BaseController
    {
        protected ModuleTrainingBLO moduleTrainingBLO = null;

		public BaseModuleTrainingsController()
        {
            this.msgHelper = new MsgHelper(typeof(ModuleTraining));
			this.moduleTrainingBLO = new ModuleTrainingBLO(this._UnitOfWork);
        }

        public virtual ActionResult Index()
        {
		   msgHelper.Index(msg);
           return View(moduleTrainingBLO.FindAll());
        }

        public virtual ActionResult Details(long? id)
        {
		    msgHelper.Details(msg);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ModuleTraining moduleTraining = moduleTrainingBLO.FindBaseEntityByID((long) id);
            if (moduleTraining == null)
            {
                return HttpNotFound();
            }
            return View(moduleTraining);
        }

        public virtual ActionResult Create()
        {
		   msgHelper.Create(msg);
			
            ViewBag.SpecialtyId = new SelectList(new SpecialtyBLO(this._UnitOfWork).FindAll(), "Id", "Code");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public virtual ActionResult Create([Bind(Include = "Id,SpecialtyId,Name,Code,Description,CreateDate,UpdateDate")] ModuleTraining moduleTraining)
        {
			
            if (ModelState.IsValid)
            {

				try
                {
                    moduleTrainingBLO.Save(moduleTraining);
                }
                catch (GAppDataBaseException ex)
                {
                    msgHelper.Create(msg);
                    Alert(ex.Message, NotificationType.error);
                    return View(moduleTraining);
                }
                
				Alert(string.Format(msgManager.The_Entity_was_well_created, msg_ModuleTraining.SingularName, moduleTraining), NotificationType.success);
                return RedirectToAction("Index");
            }
			msgHelper.Create(msg);
            ViewBag.SpecialtyId = new SelectList(new SpecialtyBLO(this._UnitOfWork).FindAll(), "Id", "Code", moduleTraining.SpecialtyId);
		    Alert(msgManager.The_information_you_have_entered_is_not_valid, NotificationType.warning);
            return View(moduleTraining);
        }

        public virtual ActionResult Edit(long? id)
        {
			msgHelper.Edit(msg);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ModuleTraining moduleTraining = moduleTrainingBLO.FindBaseEntityByID((long)id);
            if (moduleTraining == null)
            {
                return HttpNotFound();
            }
            ViewBag.SpecialtyId = new SelectList(new SpecialtyBLO(this._UnitOfWork).FindAll(), "Id", "Code", moduleTraining.SpecialtyId);
            return View(moduleTraining);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public virtual ActionResult Edit([Bind(Include = "Id,SpecialtyId,Name,Code,Description,CreateDate,UpdateDate")] ModuleTraining moduleTraining)
        {
            if (ModelState.IsValid)
            {
                ModuleTraining old_moduleTraining = moduleTrainingBLO.FindBaseEntityByID(moduleTraining.Id);
                UpdateModel(old_moduleTraining);

				try
                {
                    moduleTrainingBLO.Save(old_moduleTraining);
                }
                catch (GAppDataBaseException ex)
                {
                    msgHelper.Edit(msg); ;
                    Alert(ex.Message, NotificationType.error);
                    return View(moduleTraining);
                }

				Alert(string.Format(msgManager.The_entity_has_been_changed, msg_ModuleTraining.SingularName, moduleTraining), NotificationType.success);
                return RedirectToAction("Index");
            }
            ViewBag.SpecialtyId = new SelectList(new SpecialtyBLO(this._UnitOfWork).FindAll(), "Id", "Code", moduleTraining.SpecialtyId);

            msgHelper.Edit(msg);
			Alert(msgManager.The_information_you_have_entered_is_not_valid, NotificationType.warning);
            return View(moduleTraining);
        }

        public virtual ActionResult Delete(long? id)
        {
			msgHelper.Delete(msg);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ModuleTraining moduleTraining = moduleTrainingBLO.FindBaseEntityByID((long)id);
            if (moduleTraining == null)
            {
                return HttpNotFound();
            }
            return View(moduleTraining);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public virtual ActionResult DeleteConfirmed(long id)
        {
			ModuleTraining moduleTraining = moduleTrainingBLO.FindBaseEntityByID((long)id);
            moduleTrainingBLO.Delete(moduleTraining);

			 

			Alert(string.Format(msgManager.The_entity_has_been_removed, msg_ModuleTraining.SingularName, moduleTraining), NotificationType.success);
            return RedirectToAction("Index");
        }

		public virtual ActionResult Import()
        {
            //Save excel file to server
            HttpPostedFileBase parametersTemplate = Request.Files["import_objects"];

            // [Bug] if multiple user import the same file in the same moments
            string path = Server.MapPath("~/Content/Files/Upload" + parametersTemplate.FileName);
            if (System.IO.File.Exists(path))
            {
                System.IO.File.Delete(path);
                parametersTemplate.SaveAs(path);
            }
            parametersTemplate.SaveAs(path);

            //Save new parameters to database
            var excelData = new ExcelData(path); // link to other project
            DataTable firstTable = excelData.getFirstTable();

			try
            {
                string msg =   moduleTrainingBLO.Import(firstTable);
                Message(msg, NotificationType.info);
               
            }
            catch (ImportLineException e)
            {
                Message(e.Message, NotificationType.info);
            }
			 return RedirectToAction("Index");
        }


        public virtual FileResult Export()
        {
            using (XLWorkbook wb = new XLWorkbook())
            {
                DataTable dataTable = moduleTrainingBLO.Export();
                wb.Worksheets.Add(dataTable);
                using (MemoryStream stream = new MemoryStream())
                {
                    wb.SaveAs(stream);
                    return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", msg_ModuleTraining.PluralName + ".xlsx");
                }
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                moduleTrainingBLO.Dispose();
            }
            base.Dispose(disposing);
        }
    }

	public partial class ModuleTrainingsController : BaseModuleTrainingsController{};
}
