using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TrainingIS.DAL;
using TrainingIS.Entities;
using TrainingIS.BLL;
using GApp.DAL.ReadExcel;
using ClosedXML.Excel;
using System.IO;
using static TrainingIS.WebApp.Enums.Enums;
using TrainingIS.Entities.Resources.SeanceDayResources;
using TrainingIS.WebApp.Helpers.msgs;
using TrainingIS.WebApp.Helpers;

namespace TrainingIS.WebApp.Controllers
{
    // Generated by Manager v 0.0.5
    public class BaseSeanceDaysController : BaseController
    {
        protected SeanceDayBLO seanceDayBLO = new SeanceDayBLO();

		public BaseSeanceDaysController()
        {
            this.msgHelper = new MsgHelper(typeof(SeanceDay));
        }

        public virtual ActionResult Index()
        {
		   msgHelper.Index(msg);
           return View(seanceDayBLO.FindAll());
        }

        public virtual ActionResult Details(long? id)
        {
		    msgHelper.Details(msg);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            SeanceDay seanceDay = seanceDayBLO.FindBaseEntityByID((long) id);
            if (seanceDay == null)
            {
                return HttpNotFound();
            }
            return View(seanceDay);
        }

        public virtual ActionResult Create()
        {
		   msgHelper.Create(msg);
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public virtual ActionResult Create([Bind(Include = "Id,Name,Code,Description,CreateDate,UpdateDate")] SeanceDay seanceDay)
        {
			
            if (ModelState.IsValid)
            {
                seanceDayBLO.Save(seanceDay);
				Alert(string.Format(msgManager.The_Entity_was_well_created, msg_SeanceDay.SingularName, seanceDay), NotificationType.success);
                return RedirectToAction("Index");
            }
			msgHelper.Create(msg);
		    Alert(msgManager.The_information_you_have_entered_is_not_valid, NotificationType.warning);
            return View(seanceDay);
        }

        public virtual ActionResult Edit(long? id)
        {
			msgHelper.Edit(msg);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            SeanceDay seanceDay = seanceDayBLO.FindBaseEntityByID((long)id);
            if (seanceDay == null)
            {
                return HttpNotFound();
            }
            return View(seanceDay);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public virtual ActionResult Edit([Bind(Include = "Id,Name,Code,Description,CreateDate,UpdateDate")] SeanceDay seanceDay)
        {
            if (ModelState.IsValid)
            {
                SeanceDay old_seanceDay = seanceDayBLO.FindBaseEntityByID(seanceDay.Id);
                UpdateModel(old_seanceDay);
                seanceDayBLO.Save(old_seanceDay);
				Alert(string.Format(msgManager.The_entity_has_been_changed, msg_SeanceDay.SingularName, seanceDay), NotificationType.success);
                return RedirectToAction("Index");
            }

            msgHelper.Edit(msg);
			Alert(msgManager.The_information_you_have_entered_is_not_valid, NotificationType.warning);
            return View(seanceDay);
        }

        public virtual ActionResult Delete(long? id)
        {
			msgHelper.Delete(msg);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            SeanceDay seanceDay = seanceDayBLO.FindBaseEntityByID((long)id);
            if (seanceDay == null)
            {
                return HttpNotFound();
            }
            return View(seanceDay);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public virtual ActionResult DeleteConfirmed(long id)
        {
			SeanceDay seanceDay = seanceDayBLO.FindBaseEntityByID((long)id);
            seanceDayBLO.Delete(seanceDay);

			 

			Alert(string.Format(msgManager.The_entity_has_been_removed, msg_SeanceDay.SingularName, seanceDay), NotificationType.success);
            return RedirectToAction("Index");
        }

		public virtual ActionResult Import()
        {
            //Save excel file to server
            HttpPostedFileBase parametersTemplate = Request.Files["import_objects"];

            // [Bug] if multiple user import the same file in the same moments
            string path = Server.MapPath("~/Content/Files/Upload" + parametersTemplate.FileName);
            if (System.IO.File.Exists(path))
            {
                System.IO.File.Delete(path);
                parametersTemplate.SaveAs(path);
            }
            parametersTemplate.SaveAs(path);

            //Save new parameters to database
            var excelData = new ExcelData(path); // link to other project
            DataTable firstTable = excelData.getFirstTable();

			try
            {
                string msg =   seanceDayBLO.Import(firstTable);
                Message(msg, NotificationType.info);
               
            }
            catch (ImportLineException e)
            {
                Message(e.Message, NotificationType.info);
            }
			 return RedirectToAction("Index");
        }


        public virtual FileResult Export()
        {
            using (XLWorkbook wb = new XLWorkbook())
            {
                DataTable dataTable = seanceDayBLO.Export();
                wb.Worksheets.Add(dataTable);
                using (MemoryStream stream = new MemoryStream())
                {
                    wb.SaveAs(stream);
                    return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", msg_SeanceDay.PluralName + ".xlsx");
                }
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                seanceDayBLO.Dispose();
            }
            base.Dispose(disposing);
        }
    }

	public partial class SeanceDaysController : BaseSeanceDaysController{};
}
