using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TrainingIS.DAL;
using TrainingIS.Entities;
using TrainingIS.BLL;
using TrainingIS.BLL.Exceptions;
using GApp.DAL.ReadExcel;
using ClosedXML.Excel;
using System.IO;
using static TrainingIS.WebApp.Enums.Enums;
using TrainingIS.Entities.Resources.TrainingResources;
using TrainingIS.WebApp.Helpers.msgs;
using TrainingIS.WebApp.Helpers;
using GApp.DAL.Exceptions;

namespace TrainingIS.WebApp.Controllers
{
    // Generated by Manager v 0.1.4
    public class BaseTrainingsController : BaseController
    {
        protected TrainingBLO trainingBLO = null;

		public BaseTrainingsController()
        {
            this.msgHelper = new MsgHelper(typeof(Training));
			this.trainingBLO = new TrainingBLO(this._UnitOfWork);
        }

        public virtual ActionResult Index()
        {
		   msgHelper.Index(msg);
           return View(trainingBLO.FindAll());
        }

        public virtual ActionResult Details(long? id)
        {
		    msgHelper.Details(msg);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Training training = trainingBLO.FindBaseEntityByID((long) id);
            if (training == null)
            {
                return HttpNotFound();
            }
            return View(training);
        }

        public virtual ActionResult Create()
        {
		   msgHelper.Create(msg);
			
            ViewBag.FormerId = new SelectList(new FormerBLO(this._UnitOfWork).FindAll(), "Id", "FirstName");
			
            ViewBag.GroupId = new SelectList(new GroupBLO(this._UnitOfWork).FindAll(), "Id", "Code");
			
            ViewBag.ModuleTrainingId = new SelectList(new ModuleTrainingBLO(this._UnitOfWork).FindAll(), "Id", "Name");
			
            ViewBag.TrainingYearId = new SelectList(new TrainingYearBLO(this._UnitOfWork).FindAll(), "Id", "Code");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public virtual ActionResult Create([Bind(Include = "Id,TrainingYearId,ModuleTrainingId,FormerId,GroupId,Code,Description,CreateDate,UpdateDate")] Training training)
        {
			
            if (ModelState.IsValid)
            {

				try
                {
                    trainingBLO.Save(training);
                }
                catch (GAppDataBaseException ex)
                {
                    msgHelper.Create(msg);
                    Alert(ex.Message, NotificationType.error);
                    return View(training);
                }
                
				Alert(string.Format(msgManager.The_Entity_was_well_created, msg_Training.SingularName, training), NotificationType.success);
                return RedirectToAction("Index");
            }
			msgHelper.Create(msg);
            ViewBag.FormerId = new SelectList(new FormerBLO(this._UnitOfWork).FindAll(), "Id", "FirstName", training.FormerId);
            ViewBag.GroupId = new SelectList(new GroupBLO(this._UnitOfWork).FindAll(), "Id", "Code", training.GroupId);
            ViewBag.ModuleTrainingId = new SelectList(new ModuleTrainingBLO(this._UnitOfWork).FindAll(), "Id", "Name", training.ModuleTrainingId);
            ViewBag.TrainingYearId = new SelectList(new TrainingYearBLO(this._UnitOfWork).FindAll(), "Id", "Code", training.TrainingYearId);
		    Alert(msgManager.The_information_you_have_entered_is_not_valid, NotificationType.warning);
            return View(training);
        }

        public virtual ActionResult Edit(long? id)
        {
			msgHelper.Edit(msg);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Training training = trainingBLO.FindBaseEntityByID((long)id);
            if (training == null)
            {
                return HttpNotFound();
            }
            ViewBag.FormerId = new SelectList(new FormerBLO(this._UnitOfWork).FindAll(), "Id", "FirstName", training.FormerId);
            ViewBag.GroupId = new SelectList(new GroupBLO(this._UnitOfWork).FindAll(), "Id", "Code", training.GroupId);
            ViewBag.ModuleTrainingId = new SelectList(new ModuleTrainingBLO(this._UnitOfWork).FindAll(), "Id", "Name", training.ModuleTrainingId);
            ViewBag.TrainingYearId = new SelectList(new TrainingYearBLO(this._UnitOfWork).FindAll(), "Id", "Code", training.TrainingYearId);
            return View(training);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public virtual ActionResult Edit([Bind(Include = "Id,TrainingYearId,ModuleTrainingId,FormerId,GroupId,Code,Description,CreateDate,UpdateDate")] Training training)
        {
            if (ModelState.IsValid)
            {
                Training old_training = trainingBLO.FindBaseEntityByID(training.Id);
                UpdateModel(old_training);

				try
                {
                    trainingBLO.Save(old_training);
                }
                catch (GAppDataBaseException ex)
                {
                    msgHelper.Edit(msg); ;
                    Alert(ex.Message, NotificationType.error);
                    return View(training);
                }

				Alert(string.Format(msgManager.The_entity_has_been_changed, msg_Training.SingularName, training), NotificationType.success);
                return RedirectToAction("Index");
            }
            ViewBag.FormerId = new SelectList(new FormerBLO(this._UnitOfWork).FindAll(), "Id", "FirstName", training.FormerId);
            ViewBag.GroupId = new SelectList(new GroupBLO(this._UnitOfWork).FindAll(), "Id", "Code", training.GroupId);
            ViewBag.ModuleTrainingId = new SelectList(new ModuleTrainingBLO(this._UnitOfWork).FindAll(), "Id", "Name", training.ModuleTrainingId);
            ViewBag.TrainingYearId = new SelectList(new TrainingYearBLO(this._UnitOfWork).FindAll(), "Id", "Code", training.TrainingYearId);

            msgHelper.Edit(msg);
			Alert(msgManager.The_information_you_have_entered_is_not_valid, NotificationType.warning);
            return View(training);
        }

        public virtual ActionResult Delete(long? id)
        {
			msgHelper.Delete(msg);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Training training = trainingBLO.FindBaseEntityByID((long)id);
            if (training == null)
            {
                return HttpNotFound();
            }
            return View(training);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public virtual ActionResult DeleteConfirmed(long id)
        {
			Training training = trainingBLO.FindBaseEntityByID((long)id);
            trainingBLO.Delete(training);

			 

			Alert(string.Format(msgManager.The_entity_has_been_removed, msg_Training.SingularName, training), NotificationType.success);
            return RedirectToAction("Index");
        }

		public virtual ActionResult Import()
        {
            //Save excel file to server
            HttpPostedFileBase parametersTemplate = Request.Files["import_objects"];

            // [Bug] if multiple user import the same file in the same moments
            string path = Server.MapPath("~/Content/Files/Upload" + parametersTemplate.FileName);
            if (System.IO.File.Exists(path))
            {
                System.IO.File.Delete(path);
                parametersTemplate.SaveAs(path);
            }
            parametersTemplate.SaveAs(path);

            //Save new parameters to database
            var excelData = new ExcelData(path); // link to other project
            DataTable firstTable = excelData.getFirstTable();

			try
            {
                string msg =   trainingBLO.Import(firstTable);
                Message(msg, NotificationType.info);
               
            }
            catch (ImportLineException e)
            {
                Message(e.Message, NotificationType.info);
            }
			 return RedirectToAction("Index");
        }


        public virtual FileResult Export()
        {
            using (XLWorkbook wb = new XLWorkbook())
            {
                DataTable dataTable = trainingBLO.Export();
                wb.Worksheets.Add(dataTable);
                using (MemoryStream stream = new MemoryStream())
                {
                    wb.SaveAs(stream);
                    return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", msg_Training.PluralName + ".xlsx");
                }
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                trainingBLO.Dispose();
            }
            base.Dispose(disposing);
        }
    }

	public partial class TrainingsController : BaseTrainingsController{};
}
