using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TrainingIS.DAL;
using TrainingIS.Entities;
using TrainingIS.BLL;
using TrainingIS.BLL.Exceptions;
using GApp.DAL.ReadExcel;
using ClosedXML.Excel;
using System.IO;
using static TrainingIS.WebApp.Enums.Enums;
using TrainingIS.Entities.Resources.TrainingYearResources;
using TrainingIS.WebApp.Manager.Views.msgs;
using TrainingIS.WebApp.Helpers;
using GApp.DAL.Exceptions;

namespace TrainingIS.WebApp.Controllers
{
    // Generated by Manager v 0.1.4
    public class BaseTrainingYearsController : BaseController
    {
        protected TrainingYearBLO trainingYearBLO = null;

		public BaseTrainingYearsController()
        {
            this.msgHelper = new MsgViews(typeof(TrainingYear));
			this.trainingYearBLO = new TrainingYearBLO(this._UnitOfWork);
        }

        public virtual ActionResult Index()
        {
		   msgHelper.Index(msg);
           return View(trainingYearBLO.FindAll());
        }

        public virtual ActionResult Details(long? id)
        {
		    msgHelper.Details(msg);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            TrainingYear trainingYear = trainingYearBLO.FindBaseEntityByID((long) id);
            if (trainingYear == null)
            {
                return HttpNotFound();
            }
            return View(trainingYear);
        }

        public virtual ActionResult Create()
        {
		   msgHelper.Create(msg);
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public virtual ActionResult Create([Bind(Include = "Id,Code,StartDate,EndtDate,CreateDate,UpdateDate")] TrainingYear trainingYear)
        {
			
            if (ModelState.IsValid)
            {

				try
                {
                    trainingYearBLO.Save(trainingYear);
                }
                catch (GAppDataBaseException ex)
                {
                    msgHelper.Create(msg);
                    Alert(ex.Message, NotificationType.error);
                    return View(trainingYear);
                }
                
				Alert(string.Format(msgManager.The_Entity_was_well_created, msg_TrainingYear.SingularName, trainingYear), NotificationType.success);
                return RedirectToAction("Index");
            }
			msgHelper.Create(msg);
		    Alert(msgManager.The_information_you_have_entered_is_not_valid, NotificationType.warning);
            return View(trainingYear);
        }

        public virtual ActionResult Edit(long? id)
        {
			msgHelper.Edit(msg);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            TrainingYear trainingYear = trainingYearBLO.FindBaseEntityByID((long)id);
            if (trainingYear == null)
            {
                return HttpNotFound();
            }
            return View(trainingYear);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public virtual ActionResult Edit([Bind(Include = "Id,Code,StartDate,EndtDate,CreateDate,UpdateDate")] TrainingYear trainingYear)
        {
            if (ModelState.IsValid)
            {
                TrainingYear old_trainingYear = trainingYearBLO.FindBaseEntityByID(trainingYear.Id);
                UpdateModel(old_trainingYear);

				try
                {
                    trainingYearBLO.Save(old_trainingYear);
                }
                catch (GAppDataBaseException ex)
                {
                    msgHelper.Edit(msg); ;
                    Alert(ex.Message, NotificationType.error);
                    return View(trainingYear);
                }

				Alert(string.Format(msgManager.The_entity_has_been_changed, msg_TrainingYear.SingularName, trainingYear), NotificationType.success);
                return RedirectToAction("Index");
            }

            msgHelper.Edit(msg);
			Alert(msgManager.The_information_you_have_entered_is_not_valid, NotificationType.warning);
            return View(trainingYear);
        }

        public virtual ActionResult Delete(long? id)
        {
			msgHelper.Delete(msg);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            TrainingYear trainingYear = trainingYearBLO.FindBaseEntityByID((long)id);
            if (trainingYear == null)
            {
                return HttpNotFound();
            }
            return View(trainingYear);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public virtual ActionResult DeleteConfirmed(long id)
        {
			TrainingYear trainingYear = trainingYearBLO.FindBaseEntityByID((long)id);
            trainingYearBLO.Delete(trainingYear);

			 

			Alert(string.Format(msgManager.The_entity_has_been_removed, msg_TrainingYear.SingularName, trainingYear), NotificationType.success);
            return RedirectToAction("Index");
        }

		public virtual ActionResult Import()
        {
            //Save excel file to server
            HttpPostedFileBase parametersTemplate = Request.Files["import_objects"];

            // [Bug] if multiple user import the same file in the same moments
            string path = Server.MapPath("~/Content/Files/Upload" + parametersTemplate.FileName);
            if (System.IO.File.Exists(path))
            {
                System.IO.File.Delete(path);
                parametersTemplate.SaveAs(path);
            }
            parametersTemplate.SaveAs(path);

            //Save new parameters to database
            var excelData = new ExcelData(path); // link to other project
            DataTable firstTable = excelData.getFirstTable();

			try
            {
                string msg =   trainingYearBLO.Import(firstTable).ToString();
                Message(msg, NotificationType.info);
               
            }
            catch (ImportException e)
            {
                Message(e.Message, NotificationType.info);
            }
			 return RedirectToAction("Index");
        }


        public virtual FileResult Export()
        {
            using (XLWorkbook wb = new XLWorkbook())
            {
                DataTable dataTable = trainingYearBLO.Export();
                wb.Worksheets.Add(dataTable);
                using (MemoryStream stream = new MemoryStream())
                {
                    wb.SaveAs(stream);
                    return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", msg_TrainingYear.PluralName + ".xlsx");
                }
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                trainingYearBLO.Dispose();
            }
            base.Dispose(disposing);
        }
    }

	public partial class TrainingYearsController : BaseTrainingYearsController{};
}
