  
 
 



 
// Generated helper templates
// Generated items
// TrainingIS_UI_Tests\1_Generated_Code\Delete_Tests\Delete_Sanction_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Delete_Tests\Delete_StateOfAbsece_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Delete_Tests\Delete_Absence_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Delete_Tests\Delete_SeanceTraining_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Delete_Tests\Delete_Meeting_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Delete_Tests\Delete_SeancePlanning_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Delete_Tests\Delete_AttendanceState_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Delete_Tests\Delete_WorkGroup_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Delete_Tests\Delete_Training_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Delete_Tests\Delete_Trainee_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Delete_Tests\Delete_SanctionCategory_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Delete_Tests\Delete_WarningTrainee_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Delete_Tests\Delete_JustificationAbsence_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Delete_Tests\Delete_TaskProject_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Delete_Tests\Delete_Schedule_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Delete_Tests\Delete_Group_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Delete_Tests\Delete_Administrator_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Delete_Tests\Delete_Former_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Delete_Tests\Delete_ModuleTraining_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Delete_Tests\Delete_Specialty_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Delete_Tests\Delete_Classroom_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Delete_Tests\Delete_DisciplineCategory_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Delete_Tests\Delete_Mission_Working_Group_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Delete_Tests\Delete_Function_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Delete_Tests\Delete_Sector_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Delete_Tests\Delete_Metier_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Delete_Tests\Delete_TrainingLevel_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Delete_Tests\Delete_FormerSpecialty_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Delete_Tests\Delete_Schoollevel_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Delete_Tests\Delete_YearStudy_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Delete_Tests\Delete_SeanceNumber_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Delete_Tests\Delete_SeanceDay_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Delete_Tests\Delete_TrainingType_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Delete_Tests\Delete_TrainingYear_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Delete_Tests\Delete_Category_WarningTrainee_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Delete_Tests\Delete_Category_JustificationAbsence_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Delete_Tests\Delete_Project_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Delete_Tests\Delete_GPicture_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Delete_Tests\Delete_Nationality_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Delete_Tests\Delete_ClassroomCategory_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Delete_Tests\Delete_EntityPropertyShortcut_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Delete_Tests\Delete_AuthrorizationApp_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Delete_Tests\Delete_ActionControllerApp_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Delete_Tests\Delete_ControllerApp_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Delete_Tests\Delete_RoleApp_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Delete_Tests\Delete_LogWork_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Delete_Tests\Delete_ApplicationParam_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Delete_Tests\Delete_CalendarDay_UI_Tests_Generated.cs
