  
 
 





 
// Generated helper templates
// Generated items
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\StateOfAbseces_Details_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Absences_Details_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\SeanceTrainings_Details_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\SeancePlannings_Details_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Trainings_Details_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Trainees_Details_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\WarningTrainees_Details_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\JustificationAbsences_Details_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\TaskProjects_Details_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Schedules_Details_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Groups_Details_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Formers_Details_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\ModuleTrainings_Details_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Classrooms_Details_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Sectors_Details_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Metiers_Details_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\TrainingLevels_Details_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\FormerSpecialties_Details_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Schoollevels_Details_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Specialties_Details_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\YearStudies_Details_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\SeanceNumbers_Details_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\SeanceDays_Details_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\TrainingTypes_Details_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\TrainingYears_Details_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Category_WarningTrainees_Details_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Category_JustificationAbsences_Details_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Projects_Details_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Nationalities_Details_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\ClassroomCategories_Details_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\EntityPropertyShortcuts_Details_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\AuthrorizationApps_Details_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\ActionControllerApps_Details_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\ControllerApps_Details_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\RoleApps_Details_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\LogWorks_Details_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\ApplicationParams_Details_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\CalendarDays_Details_ControllerTests_Generated.cs
