  
 
 





 
// Generated helper templates
// Generated items
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\StateOfAbseces_Delete_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Absences_Delete_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\SeanceTrainings_Delete_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\SeancePlannings_Delete_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Trainings_Delete_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Trainees_Delete_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\WarningTrainees_Delete_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\JustificationAbsences_Delete_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\TaskProjects_Delete_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Schedules_Delete_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Groups_Delete_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Formers_Delete_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\ModuleTrainings_Delete_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Classrooms_Delete_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Sectors_Delete_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Metiers_Delete_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\TrainingLevels_Delete_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\FormerSpecialties_Delete_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Schoollevels_Delete_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Specialties_Delete_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\YearStudies_Delete_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\SeanceNumbers_Delete_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\SeanceDays_Delete_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\TrainingTypes_Delete_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\TrainingYears_Delete_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Category_WarningTrainees_Delete_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Category_JustificationAbsences_Delete_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Projects_Delete_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Nationalities_Delete_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\ClassroomCategories_Delete_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\EntityPropertyShortcuts_Delete_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\AuthrorizationApps_Delete_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\ActionControllerApps_Delete_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\ControllerApps_Delete_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\RoleApps_Delete_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\LogWorks_Delete_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\ApplicationParams_Delete_ControllerTests_Generated.cs
