  
 
 





 
// Generated helper templates
// Generated items
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\StateOfAbseces_Index_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Absences_Index_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\SeanceTrainings_Index_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\SeancePlannings_Index_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Trainings_Index_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Trainees_Index_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Schedules_Index_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Groups_Index_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Formers_Index_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\ModuleTrainings_Index_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Classrooms_Index_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Schoollevels_Index_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Specialties_Index_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\YearStudies_Index_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\SeanceNumbers_Index_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\SeanceDays_Index_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\TrainingTypes_Index_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\TrainingYears_Index_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Metiers_Index_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\TrainingLevels_Index_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Nationalities_Index_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\ClassroomCategories_Index_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\EntityPropertyShortcuts_Index_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\AuthrorizationApps_Index_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\ActionControllerApps_Index_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\ControllerApps_Index_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\RoleApps_Index_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\LogWorks_Index_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\ApplicationParams_Index_ControllerTests_Generated.cs
