  
 
 





 
// Generated helper templates
// Generated items
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\StateOfAbseces_Edit_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Absences_Edit_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\SeanceTrainings_Edit_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\SeancePlannings_Edit_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Trainings_Edit_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Trainees_Edit_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\WarningTrainees_Edit_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\JustificationAbsences_Edit_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\TaskProjects_Edit_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Schedules_Edit_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Groups_Edit_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Formers_Edit_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\ModuleTrainings_Edit_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Classrooms_Edit_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Sectors_Edit_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Metiers_Edit_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\TrainingLevels_Edit_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\FormerSpecialties_Edit_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Schoollevels_Edit_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Specialties_Edit_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\YearStudies_Edit_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\SeanceNumbers_Edit_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\SeanceDays_Edit_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\TrainingTypes_Edit_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\TrainingYears_Edit_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Category_WarningTrainees_Edit_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Category_JustificationAbsences_Edit_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Projects_Edit_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Nationalities_Edit_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\ClassroomCategories_Edit_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\EntityPropertyShortcuts_Edit_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\AuthrorizationApps_Edit_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\ActionControllerApps_Edit_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\ControllerApps_Edit_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\RoleApps_Edit_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\LogWorks_Edit_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\ApplicationParams_Edit_ControllerTests_Generated.cs
