  
 
 





 
// Generated helper templates
// Generated items
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\StateOfAbseces_Create_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Absences_Create_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\SeanceTrainings_Create_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\SeancePlannings_Create_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Trainings_Create_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Trainees_Create_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\WarningTrainees_Create_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\JustificationAbsences_Create_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\TaskProjects_Create_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Schedules_Create_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Groups_Create_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Formers_Create_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\ModuleTrainings_Create_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Classrooms_Create_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Sectors_Create_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Metiers_Create_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\TrainingLevels_Create_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\FormerSpecialties_Create_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Schoollevels_Create_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Specialties_Create_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\YearStudies_Create_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\SeanceNumbers_Create_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\SeanceDays_Create_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\TrainingTypes_Create_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\TrainingYears_Create_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Category_WarningTrainees_Create_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Category_JustificationAbsences_Create_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Projects_Create_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Nationalities_Create_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\ClassroomCategories_Create_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\EntityPropertyShortcuts_Create_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\AuthrorizationApps_Create_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\ActionControllerApps_Create_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\ControllerApps_Create_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\RoleApps_Create_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\LogWorks_Create_ControllerTests_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\ApplicationParams_Create_ControllerTests_Generated.cs
