  
 
 





 
// Generated helper templates
// Generated items
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\StateOfAbsecesControllerTests_Service_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\AbsencesControllerTests_Service_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\SeanceTrainingsControllerTests_Service_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\SeancePlanningsControllerTests_Service_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\TrainingsControllerTests_Service_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\TraineesControllerTests_Service_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\WarningTraineesControllerTests_Service_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\JustificationAbsencesControllerTests_Service_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\TaskProjectsControllerTests_Service_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\SchedulesControllerTests_Service_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\GroupsControllerTests_Service_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\FormersControllerTests_Service_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\ModuleTrainingsControllerTests_Service_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\ClassroomsControllerTests_Service_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\SectorsControllerTests_Service_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\MetiersControllerTests_Service_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\TrainingLevelsControllerTests_Service_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\FormerSpecialtiesControllerTests_Service_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\SchoollevelsControllerTests_Service_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\SpecialtiesControllerTests_Service_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\YearStudiesControllerTests_Service_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\SeanceNumbersControllerTests_Service_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\SeanceDaysControllerTests_Service_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\TrainingTypesControllerTests_Service_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\TrainingYearsControllerTests_Service_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Category_WarningTraineesControllerTests_Service_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\Category_JustificationAbsencesControllerTests_Service_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\ProjectsControllerTests_Service_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\NationalitiesControllerTests_Service_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\ClassroomCategoriesControllerTests_Service_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\EntityPropertyShortcutsControllerTests_Service_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\AuthrorizationAppsControllerTests_Service_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\ActionControllerAppsControllerTests_Service_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\ControllerAppsControllerTests_Service_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\RoleAppsControllerTests_Service_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\LogWorksControllerTests_Service_Generated.cs
// TrainingIS.WebAppTests\1_Generated_Code\Controllers\ApplicationParamsControllerTests_Service_Generated.cs
