 
 




   
// Generated helper templates
// Generated items
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Create_StateOfAbseces_UI_Create_Tests.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Create_Absences_UI_Create_Tests.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Create_SeanceTrainings_UI_Create_Tests.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Create_SeancePlannings_UI_Create_Tests.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Create_Trainings_UI_Create_Tests.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Create_Trainees_UI_Create_Tests.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Create_Schedules_UI_Create_Tests.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Create_Groups_UI_Create_Tests.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Create_Formers_UI_Create_Tests.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Create_ModuleTrainings_UI_Create_Tests.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Create_Classrooms_UI_Create_Tests.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Create_Schoollevels_UI_Create_Tests.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Create_Specialties_UI_Create_Tests.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Create_YearStudies_UI_Create_Tests.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Create_SeanceNumbers_UI_Create_Tests.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Create_SeanceDays_UI_Create_Tests.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Create_TrainingTypes_UI_Create_Tests.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Create_TrainingYears_UI_Create_Tests.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Create_Nationalities_UI_Create_Tests.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Create_ClassroomCategories_UI_Create_Tests.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Create_EntityPropertyShortcuts_UI_Create_Tests.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Create_AuthrorizationApps_UI_Create_Tests.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Create_ActionControllerApps_UI_Create_Tests.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Create_ControllerApps_UI_Create_Tests.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Create_RoleApps_UI_Create_Tests.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Create_LogWorks_UI_Create_Tests.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Create_ApplicationParams_UI_Create_Tests.cs
