  
 
 



 
// Generated helper templates
// Generated items
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Filter_Sanction_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Filter_StateOfAbsece_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Filter_Absence_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Filter_SeanceTraining_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Filter_Meeting_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Filter_SeancePlanning_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Filter_AttendanceState_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Filter_WorkGroup_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Filter_Training_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Filter_Trainee_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Filter_SanctionCategory_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Filter_WarningTrainee_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Filter_JustificationAbsence_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Filter_TaskProject_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Filter_Schedule_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Filter_Group_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Filter_Administrator_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Filter_Former_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Filter_ModuleTraining_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Filter_Specialty_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Filter_Classroom_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Filter_DisciplineCategory_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Filter_Mission_Working_Group_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Filter_Function_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Filter_Sector_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Filter_Metier_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Filter_TrainingLevel_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Filter_FormerSpecialty_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Filter_Schoollevel_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Filter_YearStudy_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Filter_SeanceNumber_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Filter_SeanceDay_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Filter_TrainingType_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Filter_TrainingYear_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Filter_Category_WarningTrainee_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Filter_Category_JustificationAbsence_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Filter_Project_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Filter_GPicture_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Filter_Nationality_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Filter_ClassroomCategory_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Filter_EntityPropertyShortcut_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Filter_AuthrorizationApp_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Filter_ActionControllerApp_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Filter_ControllerApp_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Filter_RoleApp_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Filter_LogWork_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Filter_ApplicationParam_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Actions\Filter_CalendarDay_UI_Tests_Generated.cs
