  
 

 

 
// Generated helper templates
// Generated items
// TrainingIS.BAL\1_Generated_Code\BLM\Default_Details_YearStudy_Model_Index_BLM_Generated.cs
// TrainingIS.BAL\1_Generated_Code\BLM\Default_Details_WarningTrainee_Model_Index_BLM_Generated.cs
// TrainingIS.BAL\1_Generated_Code\BLM\Default_Details_Training_Model_Index_BLM_Generated.cs
// TrainingIS.BAL\1_Generated_Code\BLM\Default_Details_TrainingYear_Model_Index_BLM_Generated.cs
// TrainingIS.BAL\1_Generated_Code\BLM\Default_Details_TrainingType_Model_Index_BLM_Generated.cs
// TrainingIS.BAL\1_Generated_Code\BLM\Default_Details_TrainingLevel_Model_Index_BLM_Generated.cs
// TrainingIS.BAL\1_Generated_Code\BLM\Default_Details_TaskProject_Model_Index_BLM_Generated.cs
// TrainingIS.BAL\1_Generated_Code\BLM\Default_Details_StateOfAbsece_Model_Index_BLM_Generated.cs
// TrainingIS.BAL\1_Generated_Code\BLM\Default_Details_Specialty_Model_Index_BLM_Generated.cs
// TrainingIS.BAL\1_Generated_Code\BLM\Default_Details_Sector_Model_Index_BLM_Generated.cs
// TrainingIS.BAL\1_Generated_Code\BLM\Default_Details_SeancePlanning_Model_Index_BLM_Generated.cs
// TrainingIS.BAL\1_Generated_Code\BLM\Default_Details_SeanceNumber_Model_Index_BLM_Generated.cs
// TrainingIS.BAL\1_Generated_Code\BLM\Default_Details_SeanceDay_Model_Index_BLM_Generated.cs
// TrainingIS.BAL\1_Generated_Code\BLM\Default_Details_Schoollevel_Model_Index_BLM_Generated.cs
// TrainingIS.BAL\1_Generated_Code\BLM\Details_Schedule_Model_Index_BLM_Generated.cs
// TrainingIS.BAL\1_Generated_Code\BLM\Default_Details_Sanction_Model_Index_BLM_Generated.cs
// TrainingIS.BAL\1_Generated_Code\BLM\Default_Details_SanctionCategory_Model_Index_BLM_Generated.cs
// TrainingIS.BAL\1_Generated_Code\BLM\Default_Details_RoleApp_Model_Index_BLM_Generated.cs
// TrainingIS.BAL\1_Generated_Code\BLM\Default_Details_Project_Model_Index_BLM_Generated.cs
// TrainingIS.BAL\1_Generated_Code\BLM\Default_Details_Nationality_Model_Index_BLM_Generated.cs
// TrainingIS.BAL\1_Generated_Code\BLM\Default_Details_Mission_Working_Group_Model_Index_BLM_Generated.cs
// TrainingIS.BAL\1_Generated_Code\BLM\Default_Details_Metier_Model_Index_BLM_Generated.cs
// TrainingIS.BAL\1_Generated_Code\BLM\Details_Meeting_Model_Index_BLM_Generated.cs
// TrainingIS.BAL\1_Generated_Code\BLM\Default_Details_LogWork_Model_Index_BLM_Generated.cs
// TrainingIS.BAL\1_Generated_Code\BLM\Default_Details_JustificationAbsence_Model_Index_BLM_Generated.cs
// TrainingIS.BAL\1_Generated_Code\BLM\IndexGroupView_Index_BLM_Generated.cs
// TrainingIS.BAL\1_Generated_Code\BLM\Default_Details_GPicture_Model_Index_BLM_Generated.cs
// TrainingIS.BAL\1_Generated_Code\BLM\Default_Details_Function_Model_Index_BLM_Generated.cs
// TrainingIS.BAL\1_Generated_Code\BLM\FormerIndexView_Index_BLM_Generated.cs
// TrainingIS.BAL\1_Generated_Code\BLM\Default_Details_FormerSpecialty_Model_Index_BLM_Generated.cs
// TrainingIS.BAL\1_Generated_Code\BLM\Default_Details_EntityPropertyShortcut_Model_Index_BLM_Generated.cs
// TrainingIS.BAL\1_Generated_Code\BLM\Default_Details_DisciplineCategory_Model_Index_BLM_Generated.cs
// TrainingIS.BAL\1_Generated_Code\BLM\Default_Details_ControllerApp_Model_Index_BLM_Generated.cs
// TrainingIS.BAL\1_Generated_Code\BLM\Default_Details_Classroom_Model_Index_BLM_Generated.cs
// TrainingIS.BAL\1_Generated_Code\BLM\Default_Details_ClassroomCategory_Model_Index_BLM_Generated.cs
// TrainingIS.BAL\1_Generated_Code\BLM\Default_Details_Category_WarningTrainee_Model_Index_BLM_Generated.cs
// TrainingIS.BAL\1_Generated_Code\BLM\Default_Details_Category_JustificationAbsence_Model_Index_BLM_Generated.cs
// TrainingIS.BAL\1_Generated_Code\BLM\Default_Details_CalendarDay_Model_Index_BLM_Generated.cs
// TrainingIS.BAL\1_Generated_Code\BLM\Default_Details_AuthrorizationApp_Model_Index_BLM_Generated.cs
// TrainingIS.BAL\1_Generated_Code\BLM\Default_Details_AttendanceState_Model_Index_BLM_Generated.cs
// TrainingIS.BAL\1_Generated_Code\BLM\Default_Details_ApplicationParam_Model_Index_BLM_Generated.cs
// TrainingIS.BAL\1_Generated_Code\BLM\Default_Details_Administrator_Model_Index_BLM_Generated.cs
// TrainingIS.BAL\1_Generated_Code\BLM\Default_Details_ActionControllerApp_Model_Index_BLM_Generated.cs
// TrainingIS.BAL\1_Generated_Code\BLM\Index_Absence_Model_Index_BLM_Generated.cs
// TrainingIS.BAL\1_Generated_Code\BLM\Index_ModuleTraining_Model_Index_BLM_Generated.cs
// TrainingIS.BAL\1_Generated_Code\BLM\Index_SeanceTraining_Model_Index_BLM_Generated.cs
// TrainingIS.BAL\1_Generated_Code\BLM\Index_Trainee_Model_Index_BLM_Generated.cs
// TrainingIS.BAL\1_Generated_Code\BLM\Default_Details_WorkGroup_Model_Index_BLM_Generated.cs
