// <auto-generated />
namespace TrainingIS.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Former_Unique_Email : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Former_Unique_Email));
        
        string IMigrationMetadata.Id
        {
            get { return "201807151921093_Former_Unique_Email"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
