// <auto-generated />
namespace TrainingIS.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Update_SeanceTraining : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_SeanceTraining));
        
        string IMigrationMetadata.Id
        {
            get { return "201808251138526_Update_SeanceTraining"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
