// <auto-generated />
namespace TrainingIS.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Update_SeanceDay : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_SeanceDay));
        
        string IMigrationMetadata.Id
        {
            get { return "201808062201058_Update_SeanceDay"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
