// <auto-generated />
namespace TrainingIS.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Update_2_Seance_Day : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_2_Seance_Day));
        
        string IMigrationMetadata.Id
        {
            get { return "201808212018298_Update_2_Seance_Day"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
