// <auto-generated />
namespace TrainingIS.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Change_WeeklyHourlyMass_to_float : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Change_WeeklyHourlyMass_to_float));
        
        string IMigrationMetadata.Id
        {
            get { return "201811051414257_Change_WeeklyHourlyMass_to_float"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
