// <auto-generated />
namespace TrainingIS.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Add_States_Column_to_Trainees : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_States_Column_to_Trainees));
        
        string IMigrationMetadata.Id
        {
            get { return "201810201112446_Add_States_Column_to_Trainees"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
