  
 
 



 
// Generated helper templates
// Generated items
// TrainingIS_UI_Tests\1_Generated_Code\Details_Tests\Details_Sanction_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Details_Tests\Details_StateOfAbsece_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Details_Tests\Details_Absence_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Details_Tests\Details_SeanceTraining_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Details_Tests\Details_Meeting_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Details_Tests\Details_SeancePlanning_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Details_Tests\Details_AttendanceState_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Details_Tests\Details_WorkGroup_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Details_Tests\Details_Training_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Details_Tests\Details_Trainee_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Details_Tests\Details_SanctionCategory_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Details_Tests\Details_WarningTrainee_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Details_Tests\Details_JustificationAbsence_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Details_Tests\Details_TaskProject_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Details_Tests\Details_Schedule_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Details_Tests\Details_Group_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Details_Tests\Details_Administrator_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Details_Tests\Details_Former_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Details_Tests\Details_ModuleTraining_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Details_Tests\Details_Specialty_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Details_Tests\Details_Classroom_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Details_Tests\Details_DisciplineCategory_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Details_Tests\Details_Mission_Working_Group_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Details_Tests\Details_Function_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Details_Tests\Details_Sector_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Details_Tests\Details_Metier_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Details_Tests\Details_TrainingLevel_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Details_Tests\Details_FormerSpecialty_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Details_Tests\Details_Schoollevel_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Details_Tests\Details_YearStudy_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Details_Tests\Details_SeanceNumber_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Details_Tests\Details_SeanceDay_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Details_Tests\Details_TrainingType_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Details_Tests\Details_TrainingYear_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Details_Tests\Details_Category_WarningTrainee_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Details_Tests\Details_Category_JustificationAbsence_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Details_Tests\Details_Project_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Details_Tests\Details_GPicture_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Details_Tests\Details_Nationality_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Details_Tests\Details_ClassroomCategory_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Details_Tests\Details_EntityPropertyShortcut_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Details_Tests\Details_AuthrorizationApp_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Details_Tests\Details_ActionControllerApp_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Details_Tests\Details_ControllerApp_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Details_Tests\Details_RoleApp_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Details_Tests\Details_LogWork_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Details_Tests\Details_ApplicationParam_UI_Tests_Generated.cs
// TrainingIS_UI_Tests\1_Generated_Code\Details_Tests\Details_CalendarDay_UI_Tests_Generated.cs
